[ package ]
    name = "hyprbar"
    version = "0.1.0"
    edition = "2024"

[ dependencies ]
    iced = { version = '0.13.1', default-features = false, features = [ 'tiny-skia', 'tokio' ] }
    iced_layershell = '0.13.7'
    chrono = '0.4.42'
    fonts = '0.2.0'
    mimalloc = '0.1.48'

[profile.dev.package."*"]
    opt-level = 3

[ profile.release ]
    opt-level = 3
    lto = 'fat'
    codegen-units = 1
    panic = 'abort'
    strip = true